# +-------------------------------------------------------------------------
# | Copyright (C) 2018 Yunify, Inc.
# +-------------------------------------------------------------------------
# | Licensed under the Apache License, Version 2.0 (the "License");
# | you may not use this work except in compliance with the License.
# | You may obtain a copy of the License in the LICENSE file, or at:
# |
# | http://www.apache.org/licenses/LICENSE-2.0
# |
# | Unless required by applicable law or agreed to in writing, software
# | distributed under the License is distributed on an "AS IS" BASIS,
# | WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# | See the License for the specific language governing permissions and
# | limitations under the License.
# +-------------------------------------------------------------------------

# In production, this needs to be in separate files.

# For StatefulSet validation
kind: Service
apiVersion: v1
metadata:
  name: csi-neonsan-controller
  namespace: kube-system
  labels:
    app: "csi-neonsan"
    role: "controller"
    csi: "v0.3.0"
    owner: "yunify"
spec:
  selector:
    app: "csi-neonsan"
    role: "controller"
    csi: "v0.3.0"
    owner: "yunify"
  ports:
    - name: dummy
      port: 12345
---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-neonsan-controller
  namespace: kube-system
spec:
  serviceName: "csi-neonsan-controller"
  selector:
    matchLabels:
      app: "csi-neonsan"
      role: "controller"
      csi: "v0.3.0"
      owner: "yunify"
  replicas: 1
  template:
    metadata:
      labels:
        app: "csi-neonsan"
        role: "controller"
        csi: "v0.3.0"
        owner: "yunify"
    spec:
      serviceAccount: csi-neonsan-controller
      imagePullSecrets:
      - name: csi-neonsan
      containers:
      - name: csi-provisioner
        image: quay.io/k8scsi/csi-provisioner:v0.3.0
        args:
        - "--provisioner=csi-neonsan"
        - "--csi-address=$(ADDRESS)"
        - "--v=5"
        env:
        - name: ADDRESS
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/csi/sockets/pluginproxy
      - name: csi-attacher
        image: quay.io/k8scsi/csi-attacher:v0.3.0
        args:
        - "--v=5"
        - "--csi-address=$(ADDRESS)"
        env:
        - name: ADDRESS
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/csi/sockets/pluginproxy
      - name: csi-neonsan
        image: dockerhub.qingcloud.com/csiplugin/csi-neonsan:latest
        args :
        - "--nodeid=$(NODE_ID)"
        - "--endpoint=$(CSI_ENDPOINT)"
        - "--v=5"
        - "--drivername=csi-neonsan"
        - "--config=/etc/neonsan/qbd.conf"
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CSI_ENDPOINT
          value: unix://var/lib/csi/sockets/pluginproxy/csi.sock
        imagePullPolicy: "Always"
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/csi/sockets/pluginproxy
        - name: server-config
          mountPath: /etc/config
        - name: neonsan-cmd
          mountPath: /usr/bin
        - name: lib
          mountPath: /lib
        - name: usrlib
          mountPath: /usr/lib
      volumes:
      - name: socket-dir
        emptyDir:
      - name: server-config
        configMap:
          name: csi-neonsan
      - name: neonsan-cmd
        hostPath:
          path: /usr/bin
          type: DirectoryOrCreate
      - name: lib
        hostPath:
          path: /lib
      - name: usrlib
        hostPath:
          path: /usr/lib
